%YAML:1.0
dataset_dir: /home/tong/Datasets/kitti/sequences/01

# camera intrinsics: KITTI 00-02
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

num_features: 150
num_features_init: 50
num_features_tracking: 50
